{% set name = "paramiko" %}
{% set version = "3.5.1" %}
{% set bundle = "tar.gz" %}
{% set hash_val = "b2c665bc45b2b215bd7d7f039901b14b067da00f3a11e6640995fd58f2664822" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash_val }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - bcrypt >=3.2
    - cryptography >=3.3
    - pynacl >=1.5

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - paramiko

about:
  home: http://www.paramiko.org/
  license_file: LICENSE
  license: LGPL-2.1-or-later
  summary: SSH2 protocol library
  license_family: LGPL
  dev_url: https://github.com/paramiko/paramiko/
  doc_url: http://docs.paramiko.org/

extra:
  recipe-maintainers:
    - vamega
    - jakirkham
    - tschoonj
