{%set name = "paramiko" %}
{%set version = "1.18.2" %}
{%set hash_type = "sha256" %}
{%set hash_val = "f49daba38450f36f74e744a9dd1e5452c861623a2f565d80e975335d8f815435" %}
{%set build_num = "0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pycrypto >=2.1,!=2.4,<3.0
    - ecdsa >=0.11,<2.0

test:
  imports:
    - paramiko

about:
  home: http://www.paramiko.org/
  license: LGPL 2.1
  license_file: LICENSE
  summary: 'SSH2 protocol library'
  license_family: LGPL
  dev_url: https://github.com/paramiko/paramiko/
  doc_url: http://docs.paramiko.org/

extra:
  recipe-maintainers:
    - pmlandwehr
    - vamega
    - jakirkham
