{% set name = "paramiko" %}
{% set version = "2.9.1" %}
{% set bundle = "tar.gz" %}
{% set hash_val = "a1fdded3b55f61d23389e4fe52d9ae428960ac958d2edf50373faa5d8926edd0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash_val }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - bcrypt >=3.1.3
    - cryptography >=2.5
    - pynacl >=1.0.1
    - six

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - paramiko

about:
  home: http://www.paramiko.org/
  license_file: LICENSE
  license: LGPL-2.1-or-later
  summary: SSH2 protocol library
  license_family: LGPL
  dev_url: https://github.com/paramiko/paramiko/
  doc_url: http://docs.paramiko.org/

extra:
  recipe-maintainers:
    - vamega
    - jakirkham
    - tschoonj
