travis:
  secure:
    BINSTAR_TOKEN: eu4mURpE/TZplImulmvQuGdV+uvaePkBfzqKhBBn+tDa87iKDmwyMSdPUI8oFB27NKUrSmTPPdvWwFUnurq5OoEYZgcmN6GA8z5UIMeOeCwYIvIzagraAvbuqKZqy9uJ7TmngOn2fwLiFiHTyS3ZW++OyH7c+1cqQI0fGpKT6AsoSBH5m0IQaFhvkmTbVY9+51l73p6ncuj1z8FJD7uQUMOVmrPusvLpKKp0ug7/MuUpP2apQbvTqRyYuGHNdfbWCMVLSMbZu00nOp7djtwuyqm5CoT6bfyf+2b48C4ITr3s2Ai34JYEzxgj9wMaK12pR9EcvK0cN4WoNn97ZwoxogOwGhwV19LkicBm5b4zG1ZMFqBPcsy+5XKGEVj2B2WMxqW9OnRhLsCHeYHQkCrTbTzJkeCud1BKTOZ1ymNQ3PsBbotTjzKm7vpC6kYznB8DRa2aObJfGfy32lZK/wA0bw2ijI2lWg8zTT1MSJabYxfqXXFvLdeX72bKzk4YOV3z+L1KwKLKHBiFjhKzdFjWZ35IY+AhgmXWXi54RjYZu9Vb8BfmaH3+3XN9jKUHKRv4/L6ExrnXrzfmdV5YCooCA3KiOVcAvpK6Jo3tpFI04IRWsxWOZnOoH+XftDG+9BujlKykCmZjzkEa2OtEWHnLbcHCcArVF0qYbK1NGr6nYrs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
